name: Optimize
on:
  - workflow_dispatch
jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge main to optimize
        run: |
          git fetch --unshallow
          git checkout main
          git checkout optimize || git checkout -b optimize
          git merge main
      - name: Run optimize-images script
        run: |
          npm install
          npm run optimize-images
      - name: Merge main to optimize
        run: |
          git add .
          git commit -m "optimization" || echo "No changes to commit"
          git push origin HEAD
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: release
          folder: content

      - name: Trigger parent module workflow
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          PARENT_REPO: ${{ secrets.PARENT_REPO }}
          PARENT_BRANCH: main
          WORKFLOW_ID: ${{ secrets.PARENT_WORKFLOW_ID }}
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
